#!/bin/bash

set -e 

function check_env_var () {
    if [ -n "$1" ]; then
      : # no-op
    else
      echo "usage: please set env var: $2"
      exit -1
    fi
}

check_env_var "$DB_USERNAME" "DB_USERNAME"
check_env_var "$DB_PASSWORD" "DB_PASSWORD"
check_env_var "$DB_URL" "DB_URL"

# ---------------
# maven 

mvn clean install -Pparents
mvn install

# ---------------
# populate ebean.properties file

EBEAN_PROPERTIES=./src/main/resources/application.properties
stat $EBEAN_PROPERTIES > /dev/null 2>&1
rm $EBEAN_PROPERTIES
touch $EBEAN_PROPERTIES

echo "# generated by $PWD/init.sh" >> $EBEAN_PROPERTIES
echo "# ebean.db.ddl.generate=true" >> $EBEAN_PROPERTIES
echo "# ebean.db.ddl.run=true" >> $EBEAN_PROPERTIES
echo "" >> $EBEAN_PROPERTIES
echo "datasource.db.username=$DB_USERNAME" >> $EBEAN_PROPERTIES
echo "datasource.db.password=$DB_PASSWORD" >> $EBEAN_PROPERTIES
echo "datasource.db.databaseUrl=$DB_URL" >> $EBEAN_PROPERTIES
echo "datasource.db.databaseDriver=org.postgresql.Driver" >> $EBEAN_PROPERTIES

echo "Ready."
